<section data-scroll-index="1" class="about">
  <div class="header">
    <div class="container">
      <h2 class="title">Como Tudo Começou?</h2>
    </div>
  </div>
  <div class="container">
    <div class="contents">
      <p>A Mais Um surgiu em 2014 após uma reportagem da TV local sobre a dificuldade do Hospital do Câncer de Londrina em conseguir R$ 100.000,00 para equipar o centro cirúrgico infantil. <br> Surgiu, então, a ideia de criar uma rede de colaboradores com a possibilidade de arrecadar e incentivar as pessoas a defenderem causas que ajudem as instituições sociais.</p>
      <img src="/assets/public/images/icons/5.png" alt="#sejamaisum">
    </div>
  </div>
</section>

<section data-scroll-index="1" class="about bg-image">
  <div class="header transparent">
    <div class="container">
      <h2 class="title">E Para Quê?</h2>
    </div>
  </div>
  <div class="container">
    <div class="contents text">
      <p class="big white">
        Nosso objetivo é criar pontes entre as pessoas, que tenham vontade de fazer a diferença realizando mudanças sociais, e as entidades assistenciais. Acreditamos que para estas entidades, é igualmente importante arrecadar recursos financeiros, e convocar pessoas do bem criando uma rede de colaboradores.      </p>
    </div>
  </div>
</section>

<section data-scroll-index="1" class="about">
  <div class="header orange">
    <div class="container">
      <h2 class="title">Por que uma rede de colaboradores?</h2>
    </div>
  </div>
  <div class="container">
    <div class="contents text">
      <p>Inspirados pela expressão “juntos podemos mais”, pensamos que quanto mais pessoas abraçarem a causa (entrando na rede), mais conteúdo será compartilhado pelo mundo, consequentemente mais pessoas poderão conhecer e apoiar as instituições sociais.</p>
      <p>Como pontapé inicial, criamos nosso perfil nas principais redes sociais convidando as pessoas à conhecerem nossa ideia. Criamos o site institucional e o aplicativo, que em breve, receberão características de rede social, e oferecerão ferramentas para que as entidades divulguem suas ações e recebam o que estão buscando na Rede Mais Um, como voluntários, investidores, doações, enfim, tudo para o bem.</p>
      <p>O desafio, agora, é movimentar a rede, incentivar o surgimento de novas ideias e reunir pessoas que apoiam as causas, para aumentar expressivamente a abrangência da Mais Um pelo país.</p>
      <p>Esperamos você na nossa rede colaborativa e, <strong>#sejamaisum</strong> mudando o mundo!!!!</p>
    </div>
  </div>
  <footer></footer>
</section>
